### ISSUE TITLE
可以选择多个图片

### ISSUE THREAD

**Issue by yaotian** [crimx/crx-weitweet#1]
目前选择图片只能选择一张，如果能支持选择多图就太好了

**Comment by crimx** [comment]
@yaotian 微博多图 API 即将下线，无法申请

**Comment by yaotian** [comment]
@crimx 用这个api可以支持多图片 http://open.weibo.com/wiki/2/statuses/upload_url_text 
 “pic_id	false	string	已经上传的图片pid，多个时使用英文半角逗号符分隔，最多不超过9个。”

**Comment by crimx** [comment]
@yaotian 说的就是它呢，看到**高级接口**了吗哈哈:smile:，还需要结合一个已经无法申请 upload_pic API

**Comment by yaotian** [comment]
@crimx 明白。不过最好申请一个高级接口，多图发帖用户体验会提高几个等级，会有更多人使用的。
