### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yaotian** [crimx/crx-weitweet#2]
fork了添加一些功能，但是
缺少oauth-client.js

**Comment by crimx** [comment]
@yaotian `oauth-clients.js` 为账号信息，可以自行添加作测试用，格式为

```
// export const twitter = {
//   id: 'xxx',
//   secret: 'xxx'
// }

// export const weibo = {
//   id: 'xxx',
//   secret: 'xxx'
// }
```

**Comment by yaotian** [comment]
` ERROR  Failed to compile with 5 errors                                                                                                                                                                 17:09:13

These relative modules were not found:

* ./oauth-client in ./src/editor/store/oauth-helper.js
* ../assets/qrcode/wechat.png in ./~/vue-loader/lib/template-compiler.js?id=data-v-ed3da552!./~/vue-loader/lib/selector.js?type=template&index=0!./src/editor/components/coffee.vue
* ../assets/qrcode/alipay.png in ./~/vue-loader/lib/template-compiler.js?id=data-v-ed3da552!./~/vue-loader/lib/selector.js?type=template&index=0!./src/editor/components/coffee.vue
* ../assets/qrcode/paypal.png in ./~/vue-loader/lib/template-compiler.js?id=data-v-ed3da552!./~/vue-loader/lib/selector.js?type=template&index=0!./src/editor/components/coffee.vue
* ../assets/qrcode/bitcoin.png in ./~/vue-loader/lib/template-compiler.js?id=data-v-ed3da552!./~/vue-loader/lib/selector.js?type=template&index=0!./src/editor/components/coffee.vue
> Listening at http://localhost:8080
`

加入了oauth-clients.js, npm run dev后的错误提示

**Comment by yaotian** [comment]
npm run build 出错
![snip20170701_2](https://user-images.githubusercontent.com/470917/27761251-de928820-5e8a-11e7-94c3-22caa2a78f50.png)

**Comment by yaotian** [comment]
npm run dev后，浏览器中错误还是提示没有找到oauth-client

![snip20170701_4](https://user-images.githubusercontent.com/470917/27761338-8a160ff4-5e8c-11e7-8181-2f8956c46f71.png)

**Comment by crimx** [comment]
@yaotian 这个文件是 oauth 授权信息，需要你自行到微博和 Twitter 上申请，同时注意在微博APP后台上设定相应的回调地址为 `https://[id].chromiumapp.org/provider_cb`，`[id]` 为扩展测试时的 ID。

文件在 `src/editor/store/oauth-clients.js`，格式为

```javascript
export const twitter = {
  id: 'xxx',
  secret: 'xxx'
}

export const weibo = {
  id: 'xxx',
  secret: 'xxx'
}
```

**Comment by yaotian** [comment]
1. twitter, weibo都已经申请，相应的值都已经写到这个文件中。
2. oauth-clients.js 名字应该是oauth-client.js吧  ，和oauth-helper.js 的“import clients from './oauth-client'” 应该一致，没错吧？

完成以上，npm run dev还是出现找不到twitter。。。这是什么原因呢?
你看到图中左边的列表中，已经存在oauth-client.js这个文件的。

**Comment by crimx** [comment]
@yaotian 嗯，对没有s，最后补上

```javascript
export default {
  twitter,
  weibo
}
```

**Comment by yaotian** [comment]
谢谢，yarn run test 可以了。但是yarn run build出如下错误。
![snip20170701_5](https://user-images.githubusercontent.com/470917/27762782-ecbcd4b2-5eaa-11e7-99b5-7155966f95df.png)

**Comment by crimx** [comment]
@yaotian 这个错误是因为 UglifyJS 不支持 ES6 语法，结合 Babel 配置查看，看哪里没有被覆盖到。

**Comment by yaotian** [comment]
如果不支持， 那你是怎么build的？

**Comment by yaotian** [comment]
![snip20170701_6](https://user-images.githubusercontent.com/470917/27763507-693dd62e-5eb7-11e7-8e92-9aba212cb331.png)
目前插件不可用？

**Comment by crimx** [comment]
Babel 会先转换为 ES5

**Comment by yaotian** [comment]
这个配置搞的好崩溃。
1. .babelrc的配置和你的是一样的。
2. package.json的配置和你的一样的。
yarn install后，理论上环境配置是一样的。babelrc中

`{
  "presets": [
    ["es2015", {
      "es2015": {
        "loose": true,
        "modules": false
      }
    }]
  ],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}
`

还手工运行了：yarn add babel-preset-es2015

我想这算配置完成了。但是 yarn run build后，还是 
`ERROR in background.js from UglifyJs
SyntaxError: Unexpected token: name (redirectCount) [background.js:9185,5]`

**Comment by yaotian** [comment]
找到bug了。
loader: 'babel-loader',
exclude: /node_modules\/(?!(get-stream|url-regex)\/).*/

第二行不对，注释掉。

**Comment by crimx** [comment]
嗯，应该是这两个库升级了。

**Comment by yaotian** [comment]
oauth-client被打包进去，不是谁都知道id,与secret了？这样是不是不安全呀

**Comment by crimx** [comment]
一般没问题，拿了也干不了什么，回调地址限定了ID，key 和 secret 也可以重新生成
